#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('AwesIO Installer', '0.2.4');
$app->add(new AwesIO\Installer\Console\NewCommand);
$app->add(new AwesIO\Installer\Console\DemoCommand);
$app->add(new AwesIO\Installer\Console\KeyCommand);
$app->add(new AwesIO\Installer\Console\TokenCommand);

$app->run();
